[sidebar]
subtitle = "韓国・POSTECH（浦項工科大学校）での研究留学の様子，学内施設，日常生活などを紹介します．"

[sidebar.avatar]
enabled = true
local = true
src = "avatar.jpg"

[article]
headingAnchor = false
math = false
readingTime = false

[colorScheme]
toggle = true
default = "light"